package main

// This script helps generate the complete seed file for all 900 Yu-Gi-Oh! The Sacred Cards
// To use: go run scripts/generate_sacred_cards_seed.go > database/migrations/003_seed_cards_complete.sql
//
// You need to populate the cardsData slice with all 900 cards from:
// https://yugioh.fandom.com/wiki/List_of_Yu-Gi-Oh!_The_Sacred_Cards_cards

import (
	"fmt"
	"os"
)

type CardData struct {
	ID          int
	Name        string
	Type        string // Monster, Spell, Trap
	Level       int
	ATK         int
	DEF         int
	Cost        int
	Description string
}

func main() {
	// TODO: Populate this with all 900 cards from the wiki
	// Format: {ID, Name, Type, Level, ATK, DEF, Cost, Description}
	cardsData := []CardData{
		{1, "Blue-Eyes White Dragon", "Monster", 8, 3000, 2500, 8, "A legendary dragon said to be invincible. Its destructive power is unmatched."},
		{35, "Dark Magician", "Monster", 7, 2500, 2100, 7, "The ultimate wizard in terms of attack and defense."},
		{82, "Red-Eyes B. Dragon", "Monster", 7, 2400, 2000, 7, "A ferocious dragon with a deadly attack."},
		{380, "Blue-Eyes Ultimate Dragon", "Monster", 12, 4500, 3800, 12, "3 \"Blue-Eyes White Dragon\""},
		{742, "Red-Eyes Black Metal Dragon", "Monster", 8, 2800, 2400, 8, "Cannot be Normal Summoned/Set. Must first be Special Summoned (from your Deck) by Tributing 1 \"Red-Eyes Black Dragon\" equipped with \"Metalmorph\"."},
		{865, "Dark Magician", "Monster", 7, 2500, 2100, 7, "The ultimate wizard in terms of attack and defense."}, // Duplicate
		{866, "Blue-Eyes Ultimate Dragon", "Monster", 12, 4500, 3800, 12, "3 \"Blue-Eyes White Dragon\""},        // Duplicate
		{884, "Red-Eyes Black Metal Dragon", "Monster", 8, 2800, 2400, 8, "Cannot be Normal Summoned/Set. Must first be Special Summoned (from your Deck) by Tributing 1 \"Red-Eyes Black Dragon\" equipped with \"Metalmorph\"."}, // Duplicate
		{885, "Red-Eyes B. Dragon", "Monster", 7, 2400, 2000, 7, "A ferocious dragon with a deadly attack."},     // Duplicate
		{887, "Blue-Eyes White Dragon", "Monster", 8, 3000, 2500, 8, "A legendary dragon said to be invincible. Its destructive power is unmatched."}, // Duplicate
		// Add remaining cards here (002-034, 036-081, 083-379, 381-741, 743-863, 868-883, 886, 888-900)
	}

	fmt.Println("-- Seed database with ALL Yu-Gi-Oh! The Sacred Cards (001-900)")
	fmt.Println("-- Generated by generate_sacred_cards_seed.go")
	fmt.Println("-- Source: https://yugioh.fandom.com/wiki/List_of_Yu-Gi-Oh!_The_Sacred_Cards_cards")
	fmt.Println("")
	fmt.Println("-- Function to safely insert a card")
	fmt.Println("CREATE OR REPLACE FUNCTION insert_sacred_card(")
	fmt.Println("    p_id INTEGER,")
	fmt.Println("    p_name VARCHAR(255),")
	fmt.Println("    p_type VARCHAR(50),")
	fmt.Println("    p_level INTEGER,")
	fmt.Println("    p_atk INTEGER,")
	fmt.Println("    p_def INTEGER,")
	fmt.Println("    p_cost INTEGER,")
	fmt.Println("    p_description TEXT DEFAULT NULL,")
	fmt.Println("    p_image VARCHAR(500) DEFAULT NULL")
	fmt.Println(") RETURNS VOID AS $$")
	fmt.Println("BEGIN")
	fmt.Println("    INSERT INTO cards (id, name, type, level, attack_points, defense_points, cost, description, image)")
	fmt.Println("    VALUES (p_id, p_name, p_type, p_level, p_atk, p_def, p_cost, p_description, p_image)")
	fmt.Println("    ON CONFLICT (id) DO UPDATE SET")
	fmt.Println("        name = EXCLUDED.name,")
	fmt.Println("        type = EXCLUDED.type,")
	fmt.Println("        level = EXCLUDED.level,")
	fmt.Println("        attack_points = EXCLUDED.attack_points,")
	fmt.Println("        defense_points = EXCLUDED.defense_points,")
	fmt.Println("        cost = EXCLUDED.cost,")
	fmt.Println("        description = EXCLUDED.description,")
	fmt.Println("        image = EXCLUDED.image;")
	fmt.Println("END;")
	fmt.Println("$$ LANGUAGE plpgsql;")
	fmt.Println("")
	fmt.Println("-- Insert all cards")

	for _, card := range cardsData {
		imageURL := fmt.Sprintf("https://images.ygoprodeck.com/images/cards/%d.jpg", card.ID)
		// Escape single quotes in description
		desc := card.Description
		desc = fmt.Sprintf("'%s'", desc)
		
		fmt.Printf("SELECT insert_sacred_card(%d, '%s', '%s', %d, %d, %d, %d, %s, '%s');\n",
			card.ID, card.Name, card.Type, card.Level, card.ATK, card.DEF, card.Cost, desc, imageURL)
	}

	fmt.Println("")
	fmt.Println("-- Clean up the function after use")
	fmt.Println("DROP FUNCTION IF EXISTS insert_sacred_card;")

	if len(cardsData) < 900 {
		fmt.Fprintf(os.Stderr, "\nWARNING: Only %d cards defined. Need to add %d more cards to reach 900.\n", 
			len(cardsData), 900-len(cardsData))
		fmt.Fprintf(os.Stderr, "Please populate cardsData slice with all cards from the wiki.\n")
	}
}

